# Generated by Django 5.1.3 on 2024-11-20 23:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('suggestion', 'Suggestion for Improvement'), ('technical_issue', 'Technical Issue'), ('general_feedback', 'General Feedback')], max_length=60)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('submission_time', models.TimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('requester', models.CharField(max_length=100)),
            ],
        ),
    ]
