# Generated by Django 5.1.3 on 2024-11-20 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformfeedback',
            name='submission_time',
        ),
        migrations.AlterField(
            model_name='platformfeedback',
            name='description',
            field=models.TextField(verbose_name='Detailed Feedback'),
        ),
        migrations.AlterField(
            model_name='platformfeedback',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FeedbackAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(verbose_name='Analysis Notes')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], max_length=30)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.platformfeedback')),
            ],
        ),
    ]
