# Generated by Django 5.1.3 on 2024-11-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_delete_feedbackanalysis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformfeedback',
            name='reporter',
            field=models.CharField(max_length=100),
        ),
    ]
