# Generated by Django 5.1.3 on 2024-11-20 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_rename_requester_platformfeedback_reporter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackanalysis',
            options={'verbose_name': 'Feedback Analysis', 'verbose_name_plural': 'Feedback Analyses'},
        ),
        migrations.AlterModelOptions(
            name='platformfeedback',
            options={'verbose_name': 'Feedback Request', 'verbose_name_plural': 'Feedback Requests'},
        ),
    ]
