# Generated by Django 5.1.3 on 2024-11-21 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_alter_feedbackanalysis_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackanalysis',
            options={},
        ),
        migrations.AlterModelOptions(
            name='platformfeedback',
            options={},
        ),
    ]
