# Generated by Django 5.1.3 on 2024-11-21 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_alter_feedbackanalysis_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackanalysis',
            options={'verbose_name': 'Feedback Analysis', 'verbose_name_plural': 'Feedback Analyses'},
        ),
        migrations.AddField(
            model_name='feedbackanalysis',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Analysis Name'),
        ),
    ]
