# Generated by Django 5.1.3 on 2024-11-21 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_alter_feedbackanalysis_options_feedbackanalysis_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackanalysis',
            name='name',
        ),
    ]
