# Generated by Django 5.1.3 on 2024-11-21 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_remove_feedbackanalysis_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackanalysis',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Analist'),
        ),
    ]
