# Generated by Django 5.1.3 on 2024-11-21 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_feedbackanalysis_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackanalysis',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Analyst Name'),
        ),
    ]
