# Generated by Django 5.1.3 on 2024-11-21 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0009_alter_feedbackanalysis_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackanalysis',
            name='name',
        ),
        migrations.AddField(
            model_name='feedbackanalysis',
            name='analyst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_analyses', to=settings.AUTH_USER_MODEL),
        ),
    ]
