# Generated by Django 5.1.3 on 2024-11-20 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SWOT', '0002_rename_analysis_period_swot_analysis_period_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swot',
            name='user_name',
        ),
        migrations.AddField(
            model_name='swot',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swots', to=settings.AUTH_USER_MODEL),
        ),
    ]
